/** Static demo data — never sent to production write APIs. */

export const DEMO_ADMIN = {
  id: 'demo-admin-1',
  name: 'Demo Admin',
  email: 'demo.admin@justedge.io',
  phone: '9000000001',
  companyName: 'Just Embedded Demo',
  role: 'Admin',
  status: 'active',
  twoFactor: false,
  permissions: {
    manageSensors: true,
    manageUsers: true,
    manageBoards: true,
    manageBilling: true,
    viewActivity: true,
    manageAccessControl: false,
    manageAdmins: false,
    manageOversight: false,
  },
  lastLogin: new Date().toISOString(),
  userCount: 1,
  subscriptionCount: 1,
  teamUsers: [
    {
      id: 'demo-user-1',
      name: 'Demo User',
      email: 'demo.user@justedge.io',
      status: 'active',
      role: 'User',
    },
  ],
};

export const DEMO_USER = {
  id: 'demo-user-1',
  name: 'Demo User',
  email: 'demo.user@justedge.io',
  phone: '9000000002',
  role: 'User',
  status: 'active',
  createdBy: 'demo-admin-1',
  permissions: {
    monitorSensors: true,
    addSensors: false,
    editSensors: false,
    removeSensors: false,
    manageAutomations: false,
    manageAlerts: false,
    manageUsers: false,
    exportData: true,
  },
};

export const DEMO_SENSORS = [
  {
    id: 'DEMO_GPS_001',
    name: 'GPS Tracker ESP32_001',
    imei: 'DEMO-IMEI-001',
    status: 'online',
    boardType: 'GPS Tracker Board',
    connectivity: 'WiFi / LTE',
    temp: 27.1,
    humidity: 48,
    battery: 78,
    lat: 12.2958,
    lng: 76.6394,
    location: '12.2958, 76.6394',
    assignedUserId: 'demo-user-1',
    assignedUserName: 'Demo User',
    subscriptionPlan: 'Pro',
    subscriptionExpiry: '2027-12-31',
    lastSeen: new Date().toISOString(),
    source: 'demo',
  },
  {
    id: 'DEMO_TEMP_001',
    name: 'Warehouse Sensor A',
    imei: 'DEMO-IMEI-002',
    status: 'online',
    boardType: 'Temperature Board',
    connectivity: 'WiFi',
    temp: 26.8,
    humidity: 52,
    battery: 92,
    lat: null,
    lng: null,
    location: '—',
    assignedUserId: 'demo-user-1',
    assignedUserName: 'Demo User',
    subscriptionPlan: 'Pro',
    subscriptionExpiry: '2027-12-31',
    lastSeen: new Date().toISOString(),
    source: 'demo',
  },
  {
    id: 'DEMO_OFFLINE_001',
    name: 'Cold Room B',
    imei: 'DEMO-IMEI-003',
    status: 'offline',
    boardType: 'Temperature Board',
    connectivity: 'WiFi',
    temp: null,
    humidity: null,
    battery: null,
    lat: null,
    lng: null,
    location: '—',
    assignedUserId: null,
    assignedUserName: null,
    subscriptionPlan: '',
    subscriptionExpiry: '',
    lastSeen: new Date(Date.now() - 86400000).toISOString(),
    source: 'demo',
  },
];

export const DEMO_ALERTS = [
  {
    id: 'demo-alert-1',
    tone: 'warn',
    title: 'High temperature',
    desc: 'Warehouse Sensor A reported 31.2°C (threshold 30°C).',
    time: '12 min ago',
    resolved: false,
    deviceId: 'DEMO_TEMP_001',
    deviceName: 'Warehouse Sensor A',
    ownerId: 'demo-user-1',
    owner: 'demo-user-1',
    createdAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-alert-2',
    tone: 'bad',
    title: 'Low battery',
    desc: 'GPS Tracker ESP32_001 battery at 18% — replace or recharge soon.',
    time: '45 min ago',
    resolved: false,
    deviceId: 'DEMO_GPS_001',
    deviceName: 'GPS Tracker ESP32_001',
    ownerId: 'demo-user-1',
    owner: 'demo-user-1',
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-alert-3',
    tone: 'warn',
    title: 'Weak signal',
    desc: 'GPS Tracker ESP32_001 signal dropped below -95 dBm near the highway corridor.',
    time: '2 hr ago',
    resolved: false,
    deviceId: 'DEMO_GPS_001',
    deviceName: 'GPS Tracker ESP32_001',
    ownerId: 'demo-user-1',
    owner: 'demo-user-1',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
];
export const DEMO_BOARD_CATALOG = [
  {
    id: 'demo-board-gps',
    name: 'GPS Tracker Board',
    conn: 'WiFi / LTE',
    probes: 1,
    desc: 'ESP32 GPS tracker with temperature probe',
  },
  {
    id: 'demo-board-temp',
    name: 'Temperature Board',
    conn: 'WiFi',
    probes: 2,
    desc: 'Warehouse temperature and humidity board',
  },
  {
    id: 'demo-board-lora',
    name: 'LoRaWAN Sensor',
    conn: 'LoRaWAN',
    probes: 1,
    desc: 'Long-range radio sensor (no SIM)',
  },
];

export const DEMO_SUBSCRIPTION_PLANS = [
  { id: 'Pro', name: 'Pro', desc: 'Full fleet features' },
  { id: 'Basic', name: 'Basic', desc: 'Core monitoring' },
];

export const DEMO_AUTOMATIONS = [
  {
    id: 'demo-auto-1',
    name: 'Over-temperature alert',
    on: true,
    ownerId: 'demo-user-1',
    owner: 'demo-user-1',
    trigger: 'temp_above',
    threshold: 30,
    action: 'create_alert',
    deviceId: 'DEMO_TEMP_001',
    deviceName: 'Warehouse Sensor A',
    desc: 'When Warehouse Sensor A exceeds 30°C, create a high-temperature alert.',
    lastRun: 'About 12 min ago',
  },
  {
    id: 'demo-auto-2',
    name: 'Low battery notify',
    on: true,
    ownerId: 'demo-user-1',
    owner: 'demo-user-1',
    trigger: 'battery_below',
    threshold: 20,
    action: 'create_alert',
    deviceId: 'DEMO_GPS_001',
    deviceName: 'GPS Tracker ESP32_001',
    desc: 'When GPS Tracker battery falls below 20%, create a low-battery alert.',
    lastRun: 'About 45 min ago',
  },
];
export const DEMO_ACTIVITY = [];
